Algoritmo "semnome"

Var
area:inteiro
base:inteiro
altura:inteiro


Inicio

escreval("Digite o valor da base do retângulo: ")
leia(base)
escreval("Digite o valor da altura do retângulo: ")
leia(altura)

area <- base * altura

escreval("O valor da área deste retângulo, com base de ",base," é: ",area)
escreval("O valor da área deste retângulo, com altura de ",altura," é: ",area)

Fimalgoritmo

