Algoritmo "semnome"

Var
area:real
base:real
altura:real


Inicio

escreval("Digite o valor da base do triângulo: ")
leia(base)
escreval("Digite o valor da altura do triângulo: ")
leia(altura)

area <- base * altura/2

escreval("O valor da área deste triângulo, com base de ",base," é: ",area)
escreval("O valor da área deste triângulo, com altura de ",altura," é: ",area)

Fimalgoritmo
